---
title: "Extra Credit: Experience Statistics!"
date: "up to 5 points on final HW total"
output: 
    html_document: 
     css: "./ec.css"
     toc: true
     toc_float: true
     fig_caption: false
---

## Introduction 

The world of statistics and data science is vast and continually growing! This extra credit assignment will help you engage with the statistics and data science communities outside of the classroom. 

## Tasks

For the extra credit assignment, you must complete the following:

1. Attend an event related to statistics or data science. This can include attending a public lecture, participating in an on-campus data science competition, etc. If you're looking for an event to attend, check out the following pages: 

    - [Department of Statistical Science Upcoming Events](https://stat.duke.edu/events)
    - [Duke Undergraduate Machine Learning Upcoming Events](https://dukeml.org/events.html)
<br>

    I would strongly encourage you to attend an in-person event, so you can engage with others in the statistics and data science community. If you are unable to attend an event, you can watch talks from rstudio::conf 2019 (https://resources.rstudio.com/rstudio-conf-2019). For the assignment, you can watch either 
    
    - 2 short talks (30 minutes or less) or 
    - 1 long talk (over 30 minutes)

2. Write a summary about the event you attended. The summary should include a brief description of the event and what you learned. As you write your summary, consider the following:
    - What is something you found particulary interesting and/or unexpected?
    - How does the event connect to something you've learned this semester?
    - What is something new you learned about the application of statistics and data science in the real-world, i.e. outside of the classroom.
    
  
## Submission & Due Dates

Please submit your write up as a Word document (.doc, .docx, .pages) or PDF document (.pdf) in the Extra Credit assignment on [Sakai](https://sakai.duke.edu/). 

**The write up must be submitted within 2 weeks of when you attended the event.**

**All extra credit must be submitted by <u>Friday, December 6 at 11:59p</u>. NO extra credit will be accepted after that deadline.**