---
title: "HW 03"
subtitle: "due Wed, Feb 19 at 11:59p"
author: ""
date: ""
output: 
  html_document:
    css: "./sta210-hw.css"
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning=FALSE,
                      message=FALSE)
```

<br><br>

*Instructions will be available when the homework is assigned.*


<!--

# Getting Started

- Go to the sta210-fa19 organization on GitHub ([https://github.com/sta210-fa19](https://github.com/sta210-fa19)). Click on the repo with the prefix **hw-03**. It contains the starter documents you need to complete the lab.
- Clone the repo in RStudio Cloud
- Configure git using the `use_git_config()` function. You can also cache your password.


## Packages 

We will use the following packages in this assignment: 

```{r}
library(tidyverse)
library(broom)
library(knitr) 
```


```{r echo=F}
derby <- read_csv("data/derbyplus.csv")
derby <- derby %>%
  mutate(year=year-1896)
```

# Questions

## Part 1: Computations & Concepts

The *Computations & Concepts* section of homework contains short answer questions about the concepts discussed in class. Some of these questions may also require short chunks of code to produce the output needed to answer the question. Answers should be written in complete sentences.

For Questions 1- 7, we will use data about the Kentucky Derby races 1896 - 2017. The Kentucky Derby is a 1.25 mile horse race held annually at the Churchill Downs race track in Louisville, Kentucky. This dataset contains information about 122 derbies held 1896 to 2017. We will use the following variables from the data:

- `year`: year of race recorded as number of years since 1896
    - e.g.: 2017 is recorded as `2017 - 1896 = 121`
- `condition`: condition of the track - fast, good, and slow.
    - "good" includes the official designations "good" and "dusty"
    - "slow" includes the official designations "slow", "heavy", "muddy", and "sloppy"
- `starters`: number of horses who raced
- `speed`: average speed of the winner (in feet per second)

Below is a regression model using `year`, `condition`, and `starters`, and `year * condition` to explain variation in `speed`. The model is shown in mathematical notation as well as in the output from R. Use the model to answer Questions 1 - 7. 


$$\hat{\text{speed}} = \hat{\beta}_0 + \hat{\beta}_1 \text{year} + \hat{\beta}_2 \text{starters} + \hat{\beta}_3 \text{good} + \hat{\beta}_4 \text{slow} + \hat{\beta}_5 (\text{year} \times \text{good}) + \hat{\beta}_6 (\text{year} \times \text{slow})$$  

```{r echo=F}
model <- lm(speed ~ year + starters + condition + year*condition, data=derby)
kable(tidy(model),format="markdown", digits = 3)
```

1. Write the equation of the model that can used to estimate  `speed` for fast track conditions. Write the equation using the estimated coefficients from R and the variable names. 

2.  Write the equation of the model that can used to estimate  `speed` for slow track conditions. Write the equation using the estimated coefficients from R and the variable names. 

3. What subset is described by the intercept? In other words, 52.387 feet per second is the average speed for the winner in what race(s)? Is the intercept meaningful? Explain.

4. Suppose we want to test if the mean winning speed is the same for fast track and good track conditions when the number of starters is held constant and  `year = 0`. What is the p-value associated with the test? 

5. Interpret the coefficient of `conditionslow` in the context of the data. Assume `year = 0`. 

6. What is the p-value for the test that the slope of year is the same for fast track conditions and good track conditions, holding year and starters constant? 

6. Use the information from the table to calculate the 95% confidence interval for the amount by which the slope of year for slow track conditions exceeds the slope of year for fast track conditions. *Hint: You can calculate t\* using the `qt()` function.*

7. Let's conduct the nested F test to test whether the slope of year is the same for all three condition types. In other words, we wish to test the hypotheses

$$ \begin{aligned} &H_0: \beta_5 = \beta_6 = 0 \\
&H_a: \text{ at least one }\beta_j \text{ is not 0}\end{aligned}$$

The residual sum of squares for the model shown above is 50.076 with 115 degrees of freedom. The residual sum of squares for the model that does not include the interaction terms between year and condition is 54.307 with 117 degrees of freedom. Calculate the F test statistic and p-value for this test. What is your conclusion? 


## Part 2: Data Analysis

The *Data Analysis* section of homework contains open-ended data analysis questions. Your response should be neatly organized and read as a complete narrative. This means that in addition to addressing the question there should also be exploratory data analysis and an analysis of the model assumptions. In short, these questions should be treated as "mini-projects".

8. `KingCountyHouses.csv` contains the price and other characteristics of over 20,000 houses sold in King County, Washington (the county that includes Seattle). The dataset includes the following variables:

- `price`: selling price of the house
- `date`: date house was sold, measured in days since January 1, 2014
- `bedrooms`: number of bedrooms
- `bathrooms`: number of bathrooms
- `sqft`: interior square footage
- `floors`: number of floors
- `waterfront`: 1 if the house has a view of the waterfront, 0 otherwise
- `yr_built`: year the house was built
- `yr_renovated`: 0 if the house was never renovated, the year the house was renovated if else

Use the code below to load the data and prepare the data.

```{r}
houses <- read_csv("data/KingCountyHouses.csv")
houses <- houses %>%
  filter(bedrooms <= 5 ) %>%
  mutate(floorsCat = as.factor(floors), 
         sqftCent = sqft - mean(sqft), 
         bedroomsCent = bedrooms - mean(bedrooms),
         bathroomsCent = bathrooms-mean(bathrooms),
         logprice = log(price))
```

Fit a regression model with `logprice` as the response and `floorsCat`, `sqftCent`, `bedroomsCent`, `bathroomsCent`, and `waterfront` as predictor variables. In your analysis, include the following: 

- Briefly explain why we should use the log-transformed version of `price` instead of the original version of the variable. 
- Describe the relationship between a house's price and square footage, including the appropriate confidence intervals. 
- Describe how the expected price differs based on the number of floors in the house. Include discussion about whether or not the differences are statistically significant.
- Consider the interaction between `waterfront` and `bedroomsCent`. Is this interaction significant? If so, describe how the relationship between `price` and `bedroomsCent` changes based on whether the house has a waterfront view.

As usual, be sure to include exploratory data analysis and an analysis of the model assumptions.


# Grading

| **Total** | **70** |
|-------------------------------------------------------------|:--:|
| Questions 1 - 7 | 30 |
| Question 8 | 30 |
| Documents complete and neatly organized (Markdown and knitted documents) | 3 |
| Answers written in complete sentences | 3 |
| Regular and informative commit messages | 4 |


## Acknowledgement

The data used in this assignment was obtained from [https://github.com/proback/BYSH](https://github.com/proback/BYSH).

-->
