---
title: "HW 06"
subtitle: "due Wed, Apr 8 at 11:59p"
author: ""
date: ""
output: 
  html_document:
    css: "./sta210-hw.css"
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning=FALSE,
                      message=FALSE)
```

<br><br>

*Instructions will be available when the homework is assigned.*


<!--
# Getting Started

- Go to the sta210-fa19 organization on GitHub ([https://github.com/sta210-fa19](https://github.com/sta210-fa19)). Click on the repo with the prefix **hw-06**. It contains the starter documents you need to complete the lab.
- Clone the repo in RStudio Cloud
- Configure git using the `use_git_config()` function. You can also cache your password.


## Packages 

Fill in the packages you need to complete the assignment in your R Markdown document. 

```{r}
library(tidyverse)
library(knitr)
library(broom)
library(nnet)

# Include other libraries as needed
```

##  The Data

For this assignment, we will analyze data from the eye witness identification experiment in [Carlson and Carlson (2014)](https://www.sciencedirect.com/science/article/pii/S2211368114000229). In this experiment, participants were asked to watch a video of a mock crime (from the first person perspective), spend a few minutes completing a random task, and then identify the perpetrator of the mock crime from a line up shown on the screen. Every lineup in this analysis included the true perpetrator from the video. After viewing the line-up , each participant could make one of the following decisions (**`id`**): 

- *correct*: correctly identified the true perpetrator
- *foil*: incorrectly identified the "foil", i.e. a person who looks very similar to the perpetrator
- *reject*: incorrectly concluded the true perpetrator is not in the lineup

The main objective of the analysis is to understand how different conditions of the mock crime and suspect lineup affect the decision made by the participant. We will consider the following conditions to describe the decisions: 

- **`lineup`**: How potential suspects are shown to the participants
    - *Simultaneous Lineup*: Participants were shown photos of all 6 potential suspects at the same time and were required to make a single decision (identify someone from the lineup or reject the lineup).
    - *Sequential 5 Lineup*: Photos of the 6 suspects were shown one at a time. The participant was required to make a decision (choose or don't choose) as each photo was shown. Once a decision was made, participants were not allowed to reexamine a photo. If the participant made an identification, the remaining photos were not shown. In each of these lineups the true perpetrator was always the 5<sup>th</sup> photo in the lineup.
- **`weapon`**:  Whether or not a weapon was present in the video of the mock crime.
- **`feature`**: Whether or not the perpetrator had a distinctive marking on his face. In this experiment, the distinctive feature was a large "N" sticker on one cheek. (The letter "N" was chosen to represent the first author's alma mater - University of Nebraska.)

Click [**here**](https://www2.stat.duke.edu/courses/Spring19/sta210.001/hw/data/eyewitness.csv) to download the data. Upload the data into the `data` folder in your RStudio Cloud project. 



# Questions 

1. Let's begin by doing the exploratory data analysis. The univariate plots for each of the predictor variables and the response variable are shown below. 

```{r echo = F}
ew <- read_csv("data/eyewitness.csv")
p1 <- ggplot(data = ew, aes(x = id)) +
  geom_bar() + 
  labs(title = "Distribution of Decision", 
       x = "id (Decision)")
p2 <- ggplot(data = ew, aes(x = lineup)) +
  geom_bar() + 
  labs(title = "Distribution of Lineup", 
       x = "Lineup")

p3 <- ggplot(data = ew, aes(x = weapon)) +
  geom_bar() + 
  labs(title = "Distribution of Weapon", 
       x = "Weapon")

p4 <- ggplot(data = ew, aes(x = feature)) +
  geom_bar() + 
  labs(title = "Distribution of Feature", 
       x = "Feature")

cowplot::plot_grid(p1, p2, p3, p4, ncol = 2)
```


Complete the exploratory data analysis by creating the plots and/or summary statistics to examine the relationship between the response variable (`id`) and each of the explanatory variables (`lineup`, `weapon`, and `feature`). 

2. Using the plots/tables from Question 1: 
    - What is one thing you learn about the data from the univariate plots?
    - Based on the bivariate plots, do any of the predictors appear to have a significant effect on the `id`? Briefly explain.


3. Briefly explain why you should use a multinomial logistic regression model to predict `id` using `lineup`, `weapon` and `feature`. 

4. Fit the multinomial logistic model that only includes main effects. Display the model output. 
    - What is the baseline category for the response variable? 
    - Interpret the intercepts for each part of the model in terms of the odds. 
    - Interpret the coefficients of `lineup` for each part of the model in terms of the odds. 
    
5. You want to consider all possible interaction effects for the model. Use the appropriate test to determine if there is at least one significant interaction effect.
    - Based on your test, is there evidence of any significant interaction effects?

*Regardless of your answer to Question 5, use the model that includes the interaction terms for the remainder of the assignment.* 

5. According to the model, 

    - If there was no weapon but the perpetrator had a distinctive feature in the mock crime, how do the <u>log-odds</u> of reject vs. a correct ID change when there is a simultaneous lineup vs. a sequential lineup? 
    - If there was no weapon but the perpetrator had a distinctive feature in the mock crime, how do the <u>odds</u> of reject vs. a correct ID change when there is a simultaneous lineup vs. a sequential lineup? 
    - Which group of participants (i.e. which set of experimental conditions) is described by the intercept?

6. The plots of the residuals versus the predicted probabilities, and the average residuals across categories of each predictor variable are shown below. Based on these plots and tables, are there any concerns with the model fit? Briefly explain. 

```{r include = F}
eye.witness <- read_csv("data/eyewitness.csv")
model2 <- multinom(id ~ lineup + weapon + feature + 
                       lineup*weapon + lineup*feature + 
                       weapon*feature,data=eye.witness)
```

```{r echo = F}
#calculate residuals by ID type
pred.probs <- data.frame(predicted = predict(model2,type="probs"))

#indicator variables for decision type
eye.witness <- eye.witness %>% 
  mutate(correct = if_else(eye.witness$id=="correct",1,0),
         foil = if_else(eye.witness$id=="foil",1,0),
         reject = if_else(eye.witness$id=="reject",1,0))

#residuals for each ID
eye.witness <- eye.witness %>%
  mutate(correct.resid = correct - pred.probs$predicted.correct,
         foil.resid = foil - pred.probs$predicted.foil,
         reject.resid = reject - pred.probs$predicted.reject)
```


```{r echo = F}
par(mfrow=c(2,2))
arm::binnedplot(x = pred.probs$predicted.correct, y = eye.witness$correct.resid, 
                main = "Correct ID: Residuals vs. Pred. Prob.", 
                xlab = "Predicted Probabilities", 
                col.int = FALSE)

arm::binnedplot(x = pred.probs$predicted.foil, y = eye.witness$foil.resid, 
                main = "Foil ID: Residuals vs. Pred. Prob.",
                xlab = "Predicted Probabilities",
                col.int = FALSE)

arm::binnedplot(x = pred.probs$predicted.reject, y = eye.witness$reject.resid, 
                main = "Reject ID: Residuals vs. Pred. Prob.",
                xlab = "Predicted Probabilities",
                col.int = FALSE)

```

```{r echo = F}
#average residuals by ID and lineup 
eye.witness %>% group_by(lineup) %>%
  summarise(correct.avg = mean(correct.resid),
            foil.avg = mean(foil.resid),
            reject.avg=mean(reject.resid))


eye.witness %>% group_by(weapon) %>%
  summarise(correct.avg = mean(correct.resid),
            foil.avg = mean(foil.resid),
            reject.avg=mean(reject.resid))

eye.witness %>% group_by(feature) %>%
  summarise(correct.avg = mean(correct.resid),
            foil.avg = mean(foil.resid),
            reject.avg=mean(reject.resid))
```


7. Use the model to predict the decision made by each participant. Make a table of the predicted vs.the actual decisions. 

    - Briefly describe how the predicted decision is determined for each participant. 
    - What is the misclassification rate? 

# References 

[Carlson, C. and Carlson, M., 2014, An evaluation of lineup presentation, weapon presence, and a distinctive feature using ROC analysis, *Journal of Applied Research in Memory and Cognition*, 3: 45-53.](https://www.sciencedirect.com/science/article/pii/S2211368114000229)


# Grading

| **Total** | **50** |
|-------------------------------------------------------------|:--:|
| Questions 1 - 5 | 40 |
| Documents complete and neatly organized (Markdown and knitted documents) | 5 |
| Answers written in complete sentences | 3 |
| Regular and informative commit messages | 2 |
-->

