---
title: "HW 05"
subtitle: "due Wed, Apr 1 at 11:59p"
date: ""
output: 
  html_document:
    css: "./sta210-hw.css"
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning=FALSE,
                      message=FALSE)
```
<br><br>

*Instructions will be available when the homework is assigned.*

<!--
# Getting Started

- Go to the sta210-fa19 organization on GitHub ([https://github.com/sta210-fa19](https://github.com/sta210-fa19)). Click on the repo with the prefix **hw-05**. It contains the starter documents you need to complete the lab.
- Clone the repo in RStudio Cloud
- Configure git using the `use_git_config()` function. You can also cache your password.


## Packages 

Fill in the packages you need to complete the assignment in your R Markdown document. 

```{r echo=F}
library(tidyverse)
library(knitr)
library(broom)
```


# Questions

## Part 1: Computations & Concepts

The *Computations & Concepts* section of homework contains short answer questions about the concepts discussed in class. Some of these questions may also require short chunks of code to produce the output needed to answer the question. Answers should be written in complete sentences. (The exercises in this section are from *Broadening Your Statistical Horizons.*)

1. In an article by  Roskes et. al. 2011, the authors report on the success rate of penalty kicks that were on-target, so that either the keeper saved the shot or the shot scored, for FIFA World Cup shootouts between 1982 and 2010. They found that 18 out of 20 shots were scored when the goalkeeper’s team was behind, 71 out of 90 shots were scored when the game was tied, and 55 out of 75 shots were scored with the goalkeeper’s team ahead.

    - Calculate the odds of a successful penalty kick for games in which the goalkeeper’s team was (i) behind, (ii) tied, or (iii) ahead.

    - Calculate the odds ratios for successful penalty kicks for (i) behind versus tied, and (ii) tied versus ahead.

2. Below is an abstract for the paper *Day Care Centers and Respiratory Health* (Nafstad et al. 1999). Interpret the odds ratios (in bold) in the context of the research study. 

    > Objective. To estimate the effects of the type of day care on respiratory health in preschool children.

    > Methods. A population-based cross-sectional study of Oslo children born in 1992 was conducted at the end of 1996. A self-administered questionnaire inquired about day care arrangements, environmental conditions, and family characteristics (n = 3853; response rate, 79%).

    > Results. In a logistic regression controlling for confounding, children in day care centers had more often nightly cough (**adjusted odds ratio, 1.89; 95% confidence interval 1.34-2.67**), and blocked or runny nose without common cold (**1.55; 1.07-1.61**) during the past 12 months compared with children in home care…

3. An article in the *Journal of Animal Ecology* by Bishop (1972) investigated whether moths provide evidence of "survival of the fittest" with their camouflage traits. Researchers glued equal numbers of light and dark morph moths in lifelike positions on tree trunks at 7 locations from 0 to 51.2 km from Liverpool. They then recorded the numbers of moths removed after 24 hours, presumably by predators. The hypothesis was that, since tree trunks near Liverpool were blackened by pollution, light morph moths would be more likely to be removed near Liverpool. The following variables are used in this analysis: 

    - `morph` = light or dark
    - `distance` = kilometers from Liverpool
    - `placed` = number of moths of a specific morph glued to trees at that location
    - `removed` = number of moths of a specific morph removed after 24 hours
    - `log_odds_removed` = log odds of being removed

The model with `log_odds_removed` as the response and `distance`, `morph`, and their interaction as the explanatory variables is shown below. 

```{r echo = F}
moth <- read_csv("data/moth.csv")
moth <- mutate(moth, notremoved = PLACED - REMOVED, 
               log_odds_removed = log(REMOVED / notremoved),
               prop_removed = REMOVED / PLACED, 
               dark = ifelse(MORPH=="dark",1,0), 
               distance = DISTANCE, 
               morph = MORPH)
```

```{r echo=F}
model1 <- lm(log_odds_removed ~ distance + morph + distance * morph, data = moth)
kable(tidy(model1, conf.int = TRUE),format = "markdown", digits = 3)
```

Interpret all the coefficients in the model (including the intercept) in terms of the **log odds** of being removed. 

4. Using the model in Question 3, interpret all the coefficients in the model (including the intercept) in terms of the **odds** of being removed. 

5. Use the model in Question 3 to calculate the predicted odds of being removed for a dark moth that is glued to the trunk of a tree that is 7.2 km from Liverpool. 

6. Use the model in Question 3 to calculate the predicted probability of being removed for a light moth that is glued to the trunk of a tree that is 41.5 km from Liverpool. 


## Part 2: Data Analysis

The *Data Analysis* section of homework contains open-ended data analysis questions. Your response should be neatly organized and read as a complete narrative. This means that in addition to addressing the question there should also be exploratory data analysis and an analysis of the model assumptions. In short, these questions should be treated as "mini-projects". (The dataset used in this section is from *Broadening Your Statistical Horizons.*)

7. The dataset `mn08.csv` has the results from the 2008 United States Presidential election for each county in Minnesota. Note that the data only includes results for the two major candidates: Democrat Barack Obama and Republican John McCain. It also contains some county-level characteristics. The following variables are in the data: 


 - `County` = county name
 - `Obama` = total votes for Obama
 - `McCain` = total votes for McCain
 - `pct_Obama` = percent of votes for Obama
 - `pct_rural` = percent of county who live in a rural setting
 - `medHHinc` = median household income
 - `unemp_rate` = unemployment rate
 - `pct_poverty` = percent living below the poverty line
 - `medAge2007` = median age in 2007
 - `medAge2000` = median age in 2000
 - `Gini_Index` = measure of income disparity in a county
 - `pct_native` = percent of native born residents

The objective of this analysis is to build a model to predict whether or not Obama would win the county in Minnesota.

Click [here](https://www2.stat.duke.edu/courses/Fall19/sta210.001/hw/data/mn08.csv) to download the data. Upload the data into the `data` folder in your RStudio Cloud project. 


- Don't forget to include exploratory data analysis of the univariate and bivariate relationships between the variables.
- Create a new variable `obama_win` that gets value "1" if Obama won the majority of the vote, and "0"" otherwise. This will be the response variable for your model.
- Use backward selection to help choose a final model that can be used to predict whether Obama would win the county. Output the final model selected and the appropriate model summary statistics. *Note: The model selected by backward selection may not be the final model. Consider all aspects of model selection and make any adjustments as necessary.* 
- In addition to the statistics associated with model selection, be sure to include an analysis of the model assumptions and model diagnostics.
- Suppose the 2020 Democratic candidate wants to use your model to strategize how to spend their campaign resources. (*For the purposes of this exercise, we'll assume a model using data from the 2008 election can still provide useful information for the 2020 election.*) They want to allocate their resources such that they're spending a lot of time and money in counties they're likely to win and less time and money in counties they're less likely to win.  Use the ROC curve to select a threshold that the candidate can use to strategize. In other words, the candidate will allocate little to no resources to counties with predicted probabilities below the threshold. 

    In your response, be sure to display the ROC curve with at least five cut-off points displayed, state your selected threshold, and briefly explain your reason for selecting the threshold.


# Grading

| **Total** | **80** |
|-------------------------------------------------------------|:--:|
| Questions 1 - 6 | 40 |
| Question 7 | 30 |
| Documents complete and neatly organized (Markdown and knitted documents) | 5 |
| Answers written in complete sentences | 3 |
| Regular and informative commit messages | 2 |


# Acknowledgement

The questions from this assignment are modified from exercises in Chapter 6 of  [*Broadening Your Statistical Horizons*](https://bookdown.org/roback/bookdown-bysh/).

# References

- Roskes, Marieke, Daniel Sligte, Shaul Shalvi, and Carsten K. W. De Dreu. 2011. “The Right Side? Under Time Pressure, Approach Motivation Leads to Right-Oriented Bias.” *Psychology Science*, 22 (11): 1403–7. doi:10.1177/0956797611418677.

- Nafstad, Per, Jorgen A. Hagen, Leif Oie, Per Magnus, and Jouni J. K. Jaakkola. 1999. “Day Care Centers and Respiratory Health.” *Pediatrics*, 103 (4): 753–58. http://pediatrics.aappublications.org/content/103/4/753.

- “NBA Enhanced Box Scores and Standings.” 2018. Accessed August 1. https://www.kaggle.com/pablote/nba-enhanced-stats.

-->
