---
title: "rstudio::conf"
subtitle: "due Fri, Jan 31 at 11:59p"
author: ""
date: ""
output: 
  html_document:
    css: "./sta210-hw.css"
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning=FALSE,
                      message=FALSE)
```

There will be no lecture meeting on Wednesday, January 30. Instead, you will take part in RStudio's annual conference, rstudio::conf. This is a great opportunity to hear from some of RStudio's primary developers and everyday users, and learn about the vast amount of things you can do with RStudio ranging from regression analysis to machine learning to creating a website to making stickers and clothes.

There are two parts to this assignment: 

**Part 1**: Watch a session from rstudio::conf

**Part 2**: Submit a short reflection 

Both parts are due by **Friday, January 31 at 11:59p**. This reflection will be worth 10 points of the HW 02 grade.

## Part 1: Watch a session from rstudio::conf

There are three ways to watch a session: 

### Option 1: Attend an on-campus rstudio::conf watch party (Wed, Jan 29 or Thu, Jan 30)

Find the full schedule and register for a session here: https://blogs.library.duke.edu/data/2020/01/13/2020-rstudio-conference-livestream-coming-to-duke-libraries/?aiEnableCheckShortcode=true

Space is limited, so register in advance! There will be swag from RStudio and some sessions include food. 


### Option 2: Watch rstudio::conf live online (Wed, Jan 29 or Thu, Jan 30)

Live stream the conference here: https://rstudio.com/conference/ and full conference schedule here: 

Have questions about the live stream? Click [here](https://community.rstudio.com/t/rstudio-conference-live-streams-questions/50937) for the live stream FAQ and [here](https://web.cvent.com/event/36ebe042-0113-44f1-8e36-b9bc5d0733bf/websitePage:34f3c2eb-9def-44a7-b324-f2d226e25011?RefId=conference&utm_campaign=Site%20Promo&utm_medium=Ste&utm_source=ConfPage) for the conference agenda. *Note: Times in the agenda are in Pacific Standard Time.*



### Option 3: Watch talks from 2019 rstudio::conf 

If you are unable to attend a watch party or watch a talk from the 2020 conference, you can watch one or two talks from the 2019 conference. 

- Find the talks from the 2019 event here: https://resources.rstudio.com/rstudio-conf-2019

- Watch either: 
    - 2 short talks (40 minutes or less) or
    - 1 long talk (over 30 minutes)
    
## Part 2: Submit a reflection

Once you've watched rstudio::conf, submit a short reflection here: https://forms.gle/4AoGyp7bGo5gE6xH6.

The reflection includes three questions: 

- What are two things you learned? 
- What is one question you still have?
- Write a Tweet to summarize the session you watched (280 characters or less).

For the email address, use NetID@duke.edu, so I can enter your reflection grade in Sakai. 


