---
title: "Remote Learning Updates"
subtitle: "Latest update: `r Sys.Date()`"
author: ""
date: ""
output: 
  html_document:
    theme: readable
    toc: true
---

This page is a summary of all the changes made to the syllabus due to the transition to the virtual classroom. **<i>Anything stated on this page supersedes the corresponding statements in the original syllabus.</i>**

Please note that this is a living document that is likely to change as we adjust to the changes. You can see the date at the top of this section to see when the document was last updated. I appreciate your patience as we navigate these circumstances together. 

If you have any general questions about the remainder of the semester, please post them using the "remote-learning" tag on [Piazza](https://piazza.com/class/k532nlvarim38u). If you have a question or comment you prefer to share privately, please email Professor Tackett. 

## Lectures

Lectures going through the course content will be pre-recorded and made available in the *Recorded Lectures & Discussions* tab in Sakai. You should watch the content videos **<u>before</u>** for our regularly scheduled meeting. See the "Class Prep" column in the [course schedule](https://www2.stat.duke.edu/courses/Spring20/sta210.001/schedule.html) for details about how to prepare for each live lecture session.

We will meet via Zoom during our regularly scheduled lecture time, MW 10:05a - 11:20a EDT. The link to join the Zoom meeting can be found at the *Zoom Class Meetings* tab on Sakai. During this time, we will review the key concepts from the pre-recorded lectures, answer any questions you have, and work in groups on practice problems. 

**<u>I strongly encourage you to attend the live lecture sessions, if possible.</u>**  This will help you keep a consistent schedule, keep up with the course content, and connect with your peers. I understand, however, that you may be in a timezone or have other circumstances that won't make this possible. All lecture sessions will be recorded and posted on Sakai. You can also post questions on pre-recorded videos in the *Recorded Lectures & Discussions* tab in Sakai, and I can will answer your questions during the scheduled lecture sessions.

## Labs

Will meet via Zoom during the regularly scheduled lab times Th 3:05p - 4:20p or 4:40p - 5:55p EDT. You can find the link to the Zoom meeting in the *Zoom Class Meetings* tab on Sakai. Your TA will do a short introduction to lab, then you will work with your lab group in Breakout Rooms to complete the lab assignment for the day. Most of the lab assignments will be aimed at helping you complete the project. 

The TAs will spend time with each group during the lab session, so I strongly encourage you attend the live lab sessions. I understand that you may be in a timezone or have other circumstances that won't make this possible, so I will provide some tips to help your group figure out a plan.

Lab sessions will <u>not</u> to be recorded.

## Office Hours

Office hours will be held via Zoom. You can find the link to the office hours session in the *Zoom Class Meetings* tab in Sakai. The office hours schedule is below (in Eastern time (EDT)). 

 <span></span>     | <span></span>  
-----------|---------------------------------
Professor Tackett | Tue 8:30a - 10a, Thu 10:30a - 12p
Youngsoo Baek | Mon 1p - 3p 
Cody Coombs | Tue 1p - 3p 
Sophie Dalldorf | Fri 1p - 3p 
Jonathan Klus | Mon 3p - 5p
Matty Pahren | Tue 3p - 5p
Ethan Shen | Wed 5p - 7p

*Note this schedule may be updated as we get more information about everyone's timezone.*


## Homework

There are no major changes to homework. There will be 3 more homework assignments, making 6 total homework assignments for the semester. I will drop the lowest homework grade at the end of the semester. 


## Late policy 

The late policy has been updated to provide flexibility during this time, while also helping you stay on top of the course work. 

Homework will be assigned on a Wednesday is due one week later on the following Wednesday at 11:59p EDT. You will have a 48-hour grace period, i.e. until Friday 11:59p EDT to turn in the homework with no late penalty. I recommend using the grace periods little as possible, but they are there to provide some stress relief.

After the 48-hour period, there is a 10% late penalty for each day the assignment is late. 

**Requests to waive late policy**. If you have extenuating circumstances that prevent you from completing an assignment by the end of the grace period, you can request to have the late penalty waived by submitting the [Late Policy Waiver Form](https://duke.qualtrics.com/jfe/form/SV_3lUoyf1YJkvBcpv). Please fill the form out only if you truly have extenuating circumstances and need additional time beyond the grace period.

## Exams

Exam 02 will be given online. It will be open-book, open-note, but you may **<u>not</u>** consult with other people. The exam will be made available **April 20 to April 22**, so you have some flexibility when you take it during that 2-day period. More details will be provided closer to the exam date.

The exam portion of your final course grade will be calculated as follows: 

The higher grade of Exam 01 & Exam 02 will be worth 25% of the final course. The lower of the two grades will be worth 15% of the final course grade.  

## Project

You will continue to work on the final project with your lab group. Some of the due dates for the project have been adjusted; see the [project instructions](https://www2.stat.duke.edu/courses/Spring20/sta210.001/project/project.html) for the updated project timeline. Most of the remaining lab sessions will be assignments specifically geared towards helping you finish the project. 

If you have circumstances that will make working in the group unfeasible and would like to complete the project individually, please fill out the [Request for Individual Project form](https://duke.qualtrics.com/jfe/form/SV_5Bj47c7BSKH5oUJ). I will follow-up with you over email with next steps.

## Teamwork & Engagement

Given the change in the semester, the Teamwork & Engagement portion of the grade will be based only on the in-class questions from January 22 - March 5. You will receive full credit for this portion of the grade if you completed at least 60% of the in-class exercises.

## Grading 

The final grade will be calculated as follows

 <span></span>     | <span></span>  
-----------|---------------------------------
Homework | 25%
Labs | 15%
Max{Exam 01, Exam 02} | 25%
Min{Exam 01, Exam 02} | 15%
Final Project | 15%
Teamwork & Engagement | 5%

By default, you are registered as S/U grading for this course (see "How Will I Be Graded" under the "Academic Continuity" section on https://keeplearning.duke.edu/ for a brief summary of this updated grading policy). If you wish to receive a letter grade for this course, you will need to submit the [S/U to Graded Form](https://registrar.duke.edu/forms/su-graded) on the Registrar's website.

The final letter grades will be assigned as follows: 

 <span></span>     | <span></span>  
-----------|---------------------------------
A | $\geq$ 93
A- | 90 - 92.22
B+ | 87 - 89.99
B | 83 - 86.99
B- | 80 - 82.99
C+ | 77 - 79.99
C | 73 - 76.99
C- | 70 - 72.99
D+ | 67 - 69.99
D | 63 - 66.99
D- | 60 - 62.99 
F  | < 60

## Additional Resources

- Up-to-date information from the Duke Administration: https://keeplearning.duke.edu/

- [Learning Online - Student Guide](https://arc.duke.edu/sites/arc.duke.edu/files/FINAL%20-%20Learning%20Online%20Student%20Guide.pdf) by the Academic Resource Center

<br><br>



[Click here](https://www2.stat.duke.edu/courses/Spring20/sta210.001/index.html) to get back to the STA 210 homepage.










